### ISSUE TITLE
"fork" is missing from page

### ISSUE THREAD

**Issue by PreetiRS** [learn-co-curriculum/phase-0-intro-to-js-2-debugging-in-node#1]
The fork button is missing beside the octocat.

**Comment by lizbur10** [comment]
Hi @PreetiRS! Thanks for spotting this issue and providing feedback!

Because this is a lesson rather than a lab, there will not be a "Fork" button on the page, so I have updated the lesson to include instructions for forking from GitHub instead. 💙
