### ISSUE TITLE
will beginning executing (grammar mistake)

### ISSUE THREAD

**Issue by SamJoma** [learn-co-curriculum/phase-0-intro-to-js-2-debugging-in-node#2]
Now if you run cont, the code will beginning executing and will pause at the first breakpoint. To continue executing the code and advance to the second breakpoint, simply enter cont again. At any point, you can enter the debugger's REPL to check the value of count, then exit the REPL and continue execution of the code.

**Comment by bal360** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
